version: '3.4'

services:
  ex0702:
    image: ex0702
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ex_07_02.py "]
    ports:
      - 5678:5678
